"""Evaluate the face similarity threshold using stored embeddings.

Loads every embeddings/student_*.pkl file, computes cosine similarity for
genuine pairs (two samples of the same student) and impostor pairs
(samples of different students), then reports FAR/FRR per threshold, the
Equal Error Rate (EER), and a suggested threshold that minimizes FAR + FRR.

Run this after enrolling enough students (>= 2 students, ideally >= 3
samples each) on the real deployment machine:

    python backend/scripts/evaluate_threshold.py
    python backend/scripts/evaluate_threshold.py --markdown --output docs/threshold_report.md

No ML models are needed - only the stored embedding pickles.
"""
import argparse
import pickle
import sys
from pathlib import Path

import numpy as np

BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from config import EMBEDDINGS_DIR, FACE_SIMILARITY_THRESHOLD

CANDIDATE_THRESHOLDS = [round(0.10 + 0.05 * i, 2) for i in range(17)]  # 0.10 .. 0.90


def load_students(embeddings_dir: Path) -> dict[int, np.ndarray]:
    """Return {student_id: matrix of embeddings} from student_*.pkl files."""
    students: dict[int, list[np.ndarray]] = {}
    for emb_file in sorted(embeddings_dir.glob("student_*.pkl")):
        try:
            student_id = int(emb_file.stem.split("_")[1])
            with open(emb_file, "rb") as f:
                vectors = pickle.load(f)
            if isinstance(vectors, list) and vectors:
                students[student_id] = np.array(vectors, dtype=np.float32)
        except (pickle.UnpicklingError, EOFError, OSError, ValueError, IndexError):
            continue
    return students


def cosine(a: np.ndarray, b: np.ndarray) -> float:
    norm_a, norm_b = np.linalg.norm(a), np.linalg.norm(b)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return float(np.dot(a, b) / (norm_a * norm_b))


def pair_similarities(students: dict[int, np.ndarray]) -> tuple[np.ndarray, np.ndarray]:
    """Genuine (same student, distinct samples) vs impostor similarities."""
    genuine: list[float] = []
    impostor: list[float] = []
    ids = sorted(students)
    for i, sid in enumerate(ids):
        vecs = students[sid]
        for a in range(len(vecs)):
            for b in range(a + 1, len(vecs)):
                genuine.append(cosine(vecs[a], vecs[b]))
        for other_id in ids[i + 1:]:
            for va in vecs:
                for vb in students[other_id]:
                    impostor.append(cosine(va, vb))
    return np.array(genuine, dtype=np.float64), np.array(impostor, dtype=np.float64)


def far_at(threshold: float, impostor: np.ndarray) -> float | None:
    """False Accept Rate: fraction of impostor pairs at/above threshold."""
    if impostor.size == 0:
        return None
    return float(np.mean(impostor >= threshold))


def frr_at(threshold: float, genuine: np.ndarray) -> float | None:
    """False Reject Rate: fraction of genuine pairs below threshold."""
    if genuine.size == 0:
        return None
    return float(np.mean(genuine < threshold))


def suggest_threshold(genuine: np.ndarray, impostor: np.ndarray) -> tuple[float, float, float]:
    """Threshold minimizing FAR + FRR. Returns (threshold, far, frr)."""
    best_t, best_far, best_frr, best_cost = FACE_SIMILARITY_THRESHOLD, 1.0, 1.0, float("inf")
    for t in CANDIDATE_THRESHOLDS:
        far, frr = far_at(t, impostor), frr_at(t, genuine)
        if far is None or frr is None:
            continue
        if far + frr < best_cost:
            best_t, best_far, best_frr, best_cost = t, far, frr, far + frr
    return best_t, best_far, best_frr


def eer(genuine: np.ndarray, impostor: np.ndarray) -> float | None:
    """Equal Error Rate (average of FAR/FRR where they are closest)."""
    if genuine.size == 0 or impostor.size == 0:
        return None
    best = None
    for t in CANDIDATE_THRESHOLDS:
        far = far_at(t, impostor) or 0.0
        frr = frr_at(t, genuine) or 0.0
        gap = abs(far - frr)
        if best is None or gap < best[0]:
            best = (gap, (far + frr) / 2)
    return best[1]


def build_report(students: dict[int, np.ndarray], genuine: np.ndarray,
                 impostor: np.ndarray, markdown: bool = False) -> str:
    lines: list[str] = []
    n_students = len(students)
    n_samples = sum(len(v) for v in students.values())

    if markdown:
        lines.append("# Face Similarity Threshold Report")
        lines.append("")
        lines.append("_Generated by `backend/scripts/evaluate_threshold.py` on real stored embeddings._")
        lines.append("")
        lines.append(f"- Students evaluated: **{n_students}**")
        lines.append(f"- Total samples: **{n_samples}**")
        lines.append(f"- Genuine pairs: **{genuine.size}**")
        lines.append(f"- Impostor pairs: **{impostor.size}**")
        lines.append("")
    else:
        lines.append(f"Students evaluated : {n_students}")
        lines.append(f"Total samples      : {n_samples}")
        lines.append(f"Genuine pairs      : {genuine.size}")
        lines.append(f"Impostor pairs     : {impostor.size}")
        lines.append("")

    if genuine.size == 0 and impostor.size == 0:
        msg = "Not enough embeddings to evaluate. Enroll at least 2 students with >= 2 samples each."
        lines.append(f"> {msg}" if markdown else msg)
        return "\n".join(lines)

    if markdown:
        lines.append("## FAR / FRR per threshold")
        lines.append("")
        lines.append("| threshold | FAR | FRR |")
        lines.append("|---|---|---|")
    else:
        lines.append("%-10s %-10s %-10s" % ("threshold", "FAR", "FRR"))
        lines.append("-" * 32)

    for t in CANDIDATE_THRESHOLDS:
        far, frr = far_at(t, impostor), frr_at(t, genuine)
        far_s = "-" if far is None else f"{far:.4f}"
        frr_s = "-" if frr is None else f"{frr:.4f}"
        if markdown:
            lines.append(f"| {t:.2f} | {far_s} | {frr_s} |")
        else:
            lines.append("%-10.2f %-10s %-10s" % (t, far_s, frr_s))

    if genuine.size and impostor.size:
        t, far, frr = suggest_threshold(genuine, impostor)
        err = eer(genuine, impostor)
        if markdown:
            lines.append("")
            lines.append("## Recommendation")
            lines.append("")
            lines.append(f"- Suggested threshold: **{t:.2f}** (FAR {far:.4f} / FRR {frr:.4f})")
            lines.append(f"- Approximate EER: **{err:.4f}**")
            lines.append(f"- Current `FACE_SIMILARITY_THRESHOLD` env: **{FACE_SIMILARITY_THRESHOLD}**")
        else:
            lines.append("")
            lines.append(f"Suggested threshold : {t:.2f} (FAR {far:.4f} / FRR {frr:.4f})")
            lines.append(f"Approximate EER     : {err:.4f}")
            lines.append(f"Current configured  : {FACE_SIMILARITY_THRESHOLD}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate face similarity threshold")
    parser.add_argument("--embeddings-dir", type=Path, default=EMBEDDINGS_DIR)
    parser.add_argument("--markdown", action="store_true", help="Print a markdown report")
    parser.add_argument("--output", type=Path, default=None, help="Also write the report to this file")
    args = parser.parse_args()

    if not args.embeddings_dir.exists():
        print(f"Embeddings dir not found: {args.embeddings_dir}")
        return 1

    students = load_students(args.embeddings_dir)
    genuine, impostor = pair_similarities(students)
    report = build_report(students, genuine, impostor, markdown=args.markdown)

    print(report)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report + "\n", encoding="utf-8")
        print(f"\nReport written to {args.output}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
